export const LANGUAGES = {
  de: {
    welcome: "Willkommen bei AleksAI. Intelegence",
    subtitle: "Dein smarter, freier KI-Begleiter",
    homeTitle: "KI-Gespräche neu definiert.",
    homeSubtitle: "Stelle unbegrenzt Fragen. Erhalte hochpräzise Antworten. Genieße kostenlosen Zugang zu Premium-Modellen.",
    placeholderHome: "Kostenlos fragen ... gewechselt auf dein Lieblingsmodell.",
    placeholderChat: "Frage AleksAI...",
    suggestedQuanten: "⚛️ Quantenphysik",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Schlaftipps",
    suggestedScharze: "🌌 Schwarze Löcher",
    advantages: "Vorteile",
    whyUs: "Warum AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 Credits täglich",
    benefitsCreditsDesc: "Erhalte jeden Tag automatisch 100 kostenlose Energie-Credits. 1 Credit entspricht einer KI-Interaktion.",
    benefitsModelsTitle: "5 KI-Modelle integriert",
    benefitsModelsDesc: "Wechsle jederzeit neben dem Login zwischen AleksAI Max, AleksAI Pro, AleksAI neo, AleksAI Ultra und AleksAI buissnis.",
    benefitsAccountTitle: "Sicheres Benutzerkonto",
    benefitsAccountDesc: "Registriere dich sicher mit einem Benutzernamen. Deine Verläufe werden privat lokal auf deinem Gerät gespeichert.",
    benefitsFreeTitle: "100% Gebührenfrei",
    benefitsFreeDesc: "Hier gibt es keine Abos oder Zahlungsdaten. Die Plattform ist und bleibt komplett frei für jeden.",
    login: "Anmelden",
    register: "Registrieren",
    guestLogin: "Als Gast anmelden",
    guestBadge: "👤 Als Gast anmelden & fortfahren",
    logout: "Abmelden",
    newChat: "Neues Gespräch",
    noChats: "Keine Verläufe vorhanden.",
    credits: "Energie-Credits",
    creditsRefilled: "🎁 Deine täglichen +100 Gratis-Credits wurden aufgeladen!",
    settings: "Einstellungen",
    settingsTitle: "Einstellungen von AleksAI. Intelegence",
    settingsModel: "Modell auswählen",
    settingsTheme: "Erscheinungsbild",
    settingsSize: "Bildschirmgröße / Ansicht",
    settingsLanguage: "Sprache wechseln",
    close: "Schließen",
    username: "Benutzername",
    password: "Passwort",
    profile: "Profil",
    chat: "Chat",
    greeting: "Hallo! Ich bin AleksAI",
    greetingDesc: "Stelle mir eine Frage — ich helfe dir bei Hausaufgaben, Coding-Aufgaben, dem Verfassen schöner Texte, kreativem Content und vielem mehr.",
    activeModelLabel: "Aktives Modell",
    noCreditsText: "⚡ Keine Credits mehr vorhanden. Morgen erhält dein Konto automatisch +100 neue Credits!",
    or: "oder",
    footerDisclaimer: "AleksAI ist vollkommen kostenlos",
    activeTheme: "Erscheinungsbild:",
    activeSize: "Ansichtsmodus:",
    activeLang: "Sprache:",
    searchBtn: "Fragen",
    selectPreferModel: "Wähle dein bevorzugtes Modell für ein Gespräch:",
    automaticSize: "Automatisch (Responsive)",
    mobileModel: "iPhone (Mobil)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Widescreen)",
    german: "Deutsch",
    english: "Englisch",
    spanish: "Spanisch",
    french: "Französisch",
    italian: "Italienisch",
    turkish: "Türkisch",
    serbian: "Serbisch",
    russian: "Russisch",
    portuguese: "Portugiesisch"
  },
  en: {
    welcome: "Welcome to AleksAI. Intelegence",
    subtitle: "Your smart, free AI companion",
    homeTitle: "AI Discussions Redefined.",
    homeSubtitle: "Ask unlimited questions. Get highly precise answers. Enjoy free access to premium models.",
    placeholderHome: "Ask for free ... switched to your favorite model.",
    placeholderChat: "Ask AleksAI...",
    suggestedQuanten: "⚛️ Quantum physics",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Sleep tips",
    suggestedScharze: "🌌 Black Holes",
    advantages: "Advantages",
    whyUs: "Why AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 daily credits",
    benefitsCreditsDesc: "Automatically get 100 free energy credits daily. 1 credit equals 1 AI interaction.",
    benefitsModelsTitle: "5 integrated AI models",
    benefitsModelsDesc: "Switch anytime between AleksAI Max, Pro, neo, Ultra, and buissnis.",
    benefitsAccountTitle: "Secure user account",
    benefitsAccountDesc: "Register securely with a username. Your histories are stored privately on your device.",
    benefitsFreeTitle: "100% Free of charge",
    benefitsFreeDesc: "No subscriptions or payment details. The platform remains completely free for everyone.",
    login: "Login",
    register: "Register",
    guestLogin: "Login as Guest",
    guestBadge: "👤 Login as Guest & continue",
    logout: "Logout",
    newChat: "New Conversation",
    noChats: "No histories available.",
    credits: "Energy Credits",
    creditsRefilled: "🎁 Your daily +100 free credits have been refilled!",
    settings: "Settings",
    settingsTitle: "Settings of AleksAI. Intelegence",
    settingsModel: "Select Model",
    settingsTheme: "Theme",
    settingsSize: "Screen Size / Mode",
    settingsLanguage: "Change Language",
    close: "Close",
    username: "Username",
    password: "Password",
    profile: "Profile",
    chat: "Chat",
    greeting: "Hello! I am AleksAI",
    greetingDesc: "Ask me anything — I help with homework, coding tasks, writing beautiful texts, creative content, and much more.",
    activeModelLabel: "Active Model",
    noCreditsText: "⚡ No credits remaining. Your account gets another +100 credits automatically tomorrow!",
    or: "or",
    footerDisclaimer: "AleksAI is completely free",
    activeTheme: "Appearance:",
    activeSize: "View Mode:",
    activeLang: "Language:",
    searchBtn: "Ask",
    selectPreferModel: "Select your preferred model for a conversation:",
    automaticSize: "Automatic (Responsive)",
    mobileModel: "iPhone (Mobile)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Widescreen)",
    german: "German",
    english: "English",
    spanish: "Spanish",
    french: "French",
    italian: "Italian",
    turkish: "Turkish",
    serbian: "Serbian",
    russian: "Russian",
    portuguese: "Portuguese"
  },
  es: {
    welcome: "Bienvenido a AleksAI. Intelegence",
    subtitle: "Tu compañero inteligente y gratuito de IA",
    homeTitle: "Conversaciones de IA Redefinidas.",
    homeSubtitle: "Haz preguntas ilimitadas. Obtén respuestas de alta precisión. Disfruta de acceso gratuito a modelos premium.",
    placeholderHome: "Pregunta gratis ... cambiado a tu modelo favorito.",
    placeholderChat: "Pregúntale a AleksAI...",
    suggestedQuanten: "⚛️ Física cuántica",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Consejos para dormir",
    suggestedScharze: "🌌 Agujeros negros",
    advantages: "Ventajas",
    whyUs: "¿Por qué AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 créditos diarios",
    benefitsCreditsDesc: "Recibe automáticamente 100 créditos de energía gratuitos al día. 1 crédito equivale a 1 interacción de IA.",
    benefitsModelsTitle: "5 modelos de IA integrados",
    benefitsModelsDesc: "Cambia en cualquier momento entre AleksAI Max, Pro, neo, Ultra y buissnis.",
    benefitsAccountTitle: "Cuenta de usuario segura",
    benefitsAccountDesc: "Regístrate de forma segura con un nombre de usuario. Tu historial se guarda de manera privada en tu dispositivo.",
    benefitsFreeTitle: "100% Gratis",
    benefitsFreeDesc: "Sin suscripciones ni datos de pago. El sistema es y seguirá siendo completamente gratuito para todos.",
    login: "Iniciar sesión",
    register: "Registrarse",
    guestLogin: "Iniciar sesión como invitado",
    guestBadge: "👤 Entrar como invitado y continuar",
    logout: "Cerrar sesión",
    newChat: "Nueva conversación",
    noChats: "No hay conversaciones disponibles.",
    credits: "Créditos de energía",
    creditsRefilled: "🎁 ¡Tus +100 créditos diarios gratuitos han sido recargados!",
    settings: "Configuración",
    settingsTitle: "Configuraciones de AleksAI. Intelegence",
    settingsModel: "Seleccionar modelo",
    settingsTheme: "Apariencia",
    settingsSize: "Tamaño de pantalla / Modo",
    settingsLanguage: "Cambiar idioma",
    close: "Cerrar",
    username: "Nombre de usuario",
    password: "Contraseña",
    profile: "Perfil",
    chat: "Chat",
    greeting: "¡Hola! Soy AleksAI",
    greetingDesc: "Hazme una pregunta — te ayudo con las tareas de la escuela, programación, redacción de textos hermosos, contenido creativo y mucho más.",
    activeModelLabel: "Modelo activo",
    noCreditsText: "⚡ Sin créditos disponibles. ¡Tu cuenta recibirá +100 créditos automáticamente mañana!",
    or: "o",
    footerDisclaimer: "AleksAI es completamente gratuito",
    activeTheme: "Apariencia:",
    activeSize: "Modo de Vista:",
    activeLang: "Idioma:",
    searchBtn: "Preguntar",
    selectPreferModel: "Selecciona tu modelo preferido para conversar:",
    automaticSize: "Automático (Responsive)",
    mobileModel: "iPhone (Móvil)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Widescreen)",
    german: "Alemán",
    english: "Inglés",
    spanish: "Español",
    french: "Francés",
    italian: "Italiano",
    turkish: "Turco",
    serbian: "Serbio",
    russian: "Ruso",
    portuguese: "Portugués"
  },
  fr: {
    welcome: "Bienvenue sur AleksAI. Intelegence",
    subtitle: "Votre compagnon IA intelligent et gratuit",
    homeTitle: "Les discussions IA réinventées.",
    homeSubtitle: "Posez des questions illimitées. Obtenez des réponses ultra-précises. Profitez d'un accès gratuit aux modèles premium.",
    placeholderHome: "Demandez gratuitement ... basculé vers votre modèle préféré.",
    placeholderChat: "Demander à AleksAI...",
    suggestedQuanten: "⚛️ Physique quantique",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Conseils sommeil",
    suggestedScharze: "🌌 Trous noirs",
    advantages: "Avantages",
    whyUs: "Pourquoi AleksAI. Intelegence ?",
    benefitsCreditsTitle: "+100 crédits quotidiens",
    benefitsCreditsDesc: "Recevez automatiquement 100 crédits d'énergie gratuits par jour. 1 crédit équivaut à 1 interaction IA.",
    benefitsModelsTitle: "5 modèles d'IA intégrés",
    benefitsModelsDesc: "Basculez à tout moment entre AleksAI Max, Pro, neo, Ultra et buissnis.",
    benefitsAccountTitle: "Compte utilisateur sécurisé",
    benefitsAccountDesc: "Inscrivez-vous en toute sécurité avec un pseudonyme. Votre historique est enregistré localement sur votre appareil.",
    benefitsFreeTitle: "100% Gratuit",
    benefitsFreeDesc: "Pas d'abonnements, pas de coordonnées bancaires. La plateforme est et restera entièrement gratuite pour tous.",
    login: "Se connecter",
    register: "S'inscrire",
    guestLogin: "Connexion invité",
    guestBadge: "👤 Se connecter en tant qu'invité et continuer",
    logout: "Se déconnecter",
    newChat: "Nouvelle discussion",
    noChats: "Aucun historique disponible.",
    credits: "Crédits d'énergie",
    creditsRefilled: "🎁 Vos +100 crédits gratuits quotidiens ont été rechargés !",
    settings: "Paramètres",
    settingsTitle: "Paramètres d'AleksAI. Intelegence",
    settingsModel: "Choisir un modèle",
    settingsTheme: "Apparence",
    settingsSize: "Vue écran / Mode",
    settingsLanguage: "Changer de langue",
    close: "Fermer",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    profile: "Profil",
    chat: "Chat",
    greeting: "Bonjour ! Je suis AleksAI",
    greetingDesc: "Pose-moi une question — je t'aide pour tes devoirs, tes projets de programmation, la rédaction de jolis textes, du contenu créatif et bien plus encore.",
    activeModelLabel: "Modèle actif",
    noCreditsText: "⚡ Plus de crédits disponibles. Votre compte en recevra +100 automatiquement demain !",
    or: "ou",
    footerDisclaimer: "AleksAI est entièrement gratuit",
    activeTheme: "Apparence:",
    activeSize: "Mode d'affichage:",
    activeLang: "Langue:",
    searchBtn: "Demander",
    selectPreferModel: "Sélectionnez votre modèle préféré pour discuter :",
    automaticSize: "Automatique (Responsive)",
    mobileModel: "iPhone (Mobile)",
    tabletModel: "iPad (Tablette)",
    desktopModel: "PC (Widescreen)",
    german: "Allemand",
    english: "Anglais",
    spanish: "Espagnol",
    french: "Français",
    italian: "Italien",
    turkish: "Turc",
    serbian: "Serbe",
    russian: "Russe",
    portuguese: "Portugais"
  },
  it: {
    welcome: "Benvenuto su AleksAI. Intelegence",
    subtitle: "Il tuo assistente IA intelligente e gratuito",
    homeTitle: "Discussioni IA ridefinite.",
    homeSubtitle: "Fai domande illimitate. Ottieni risposte ad alta precisione. Goditi l'accesso gratuito ai modelli premium.",
    placeholderHome: "Chiedi gratis ... passato al tuo modello preferito.",
    placeholderChat: "Chiedi a AleksAI...",
    suggestedQuanten: "⚛️ Fisica quantistica",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Consigli sonno",
    suggestedScharze: "🌌 Buchi neri",
    advantages: "Vantaggi",
    whyUs: "Perché AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 crediti giornalieri",
    benefitsCreditsDesc: "Ottieni 100 crediti gratuiti ogni giorno in automatico. 1 credito equivale a 1 interazione IA.",
    benefitsModelsTitle: "5 modelli IA integrati",
    benefitsModelsDesc: "Passa in ogni momento tra AleksAI Max, Pro, neo, Ultra e buissnis.",
    benefitsAccountTitle: "Account utente sicuro",
    benefitsAccountDesc: "Registrati in modo sicuro con un nome utente. La cronologia delle chat è memorizzata sul dispositivo.",
    benefitsFreeTitle: "100% Gratuito",
    benefitsFreeDesc: "Nessun abbonamento, nessun dato di pagamento. La piattaforma è e rimarrà del tutto gratuita per tutti.",
    login: "Accedi",
    register: "Registrati",
    guestLogin: "Accedi come ospite",
    guestBadge: "👤 Accedi come Ospite e continua",
    logout: "Disconnetti",
    newChat: "Nuova chat",
    noChats: "Nessuna cronologia disponibile.",
    credits: "Crediti energetici",
    creditsRefilled: "🎁 I tuoi +100 crediti giornalieri gratuiti sono stati ricaricati!",
    settings: "Impostazioni",
    settingsTitle: "Impostazioni di AleksAI. Intelegence",
    settingsModel: "Seleziona modello",
    settingsTheme: "Aspetto",
    settingsSize: "Dimensione schermo / Vista",
    settingsLanguage: "Cambia lingua",
    close: "Chiudi",
    username: "Nome utente",
    password: "Password",
    profile: "Profilo",
    chat: "Chat",
    greeting: "Ciao! Sono AleksAI",
    greetingDesc: "Fammi una domanda — posso aiutarti con i compiti, la programmazione, scrivere bellissimi testi, contenuti creativi e molto altro.",
    activeModelLabel: "Modello attivo",
    noCreditsText: "⚡ Crediti esauriti. Domani riceverai automaticamente +100 crediti gratis!",
    or: "o",
    footerDisclaimer: "AleksAI è del tutto gratuito",
    activeTheme: "Aspetto:",
    activeSize: "Modalità di visualizzazione:",
    activeLang: "Lingua:",
    searchBtn: "Chiedi",
    selectPreferModel: "Seleziona il tuo modello preferito con cui dialogare:",
    automaticSize: "Automatico (Responsive)",
    mobileModel: "iPhone (Mobile)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Widescreen)",
    german: "Tedesco",
    english: "Inglese",
    spanish: "Spagnolo",
    french: "Francese",
    italian: "Italiano",
    turkish: "Turco",
    serbian: "Serbo",
    russian: "Russo",
    portuguese: "Portoghese"
  },
  tr: {
    welcome: "AleksAI. Intelegence'a Hoş Geldiniz",
    subtitle: "Sizin akıllı ve ücretsiz yapay zekâ yardımcınız",
    homeTitle: "Yapay Zekâ Sohbetleri Yeniden Tanımlandı.",
    homeSubtitle: "Sınırsız soru sorun. Son derece kesin yanıtlar alın. Premium modellere ücretsiz erişimin tadını çıkarın.",
    placeholderHome: "Ücretsiz olarak sor ... en beğendiğin modele geçiş yapıldı.",
    placeholderChat: "AleksAI'a sor...",
    suggestedQuanten: "⚛️ Kuantum fiziği",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Uyku ipuçları",
    suggestedScharze: "🌌 Kara Delikler",
    advantages: "Avantajlar",
    whyUs: "Neden AleksAI. Intelegence?",
    benefitsCreditsTitle: "Her Gün +100 Kredi",
    benefitsCreditsDesc: "Her gün otomatik olarak 100 ücretsiz enerji kredisi kazanın. 1 kredi, 1 yapay zekâ etkileşimine eşittir.",
    benefitsModelsTitle: "5 Entegre Yapay Zekâ Modeli",
    benefitsModelsDesc: "AleksAI Max, Pro, neo, Ultra ve buissnis arasında dilediğiniz an geçiş yapın.",
    benefitsAccountTitle: "Güvenli Kullanıcı Hesabı",
    benefitsAccountDesc: "Bir kullanıcı adı ile güvenli bir şekilde kaydolun. Sohbet geçmişleriniz cihazınızda özel olarak saklanır.",
    benefitsFreeTitle: "%100 Ücretsiz",
    benefitsFreeDesc: "Abonelik yok, ödeme bilgisi gerekmez. Platform herkes için tamamen ücretsizdir ve ücretsiz kalacaktır.",
    login: "Giriş Yap",
    register: "Kayıt Ol",
    guestLogin: "Misafir Girişi",
    guestBadge: "👤 Misafir Olarak Giriş Yap & Devam Et",
    logout: "Çıkış Yap",
    newChat: "Yeni Sohbet",
    noChats: "Sohbet geçmişi bulunmuyor.",
    credits: "Enerji Kredileri",
    creditsRefilled: "🎁 Günlük +100 ücretsiz krediniz başarıyla yüklendi!",
    settings: "Ayarlar",
    settingsTitle: "AleksAI. Intelegence Ayarları",
    settingsModel: "Model Seç",
    settingsTheme: "Görünüm",
    settingsSize: "Ekran Boyutu / Görünüm",
    settingsLanguage: "Dil Değiştir",
    close: "Kapat",
    username: "Kullanıcı Adı",
    password: "Şifre",
    profile: "Profil",
    chat: "Sohbet",
    greeting: "Merhaba! Ben AleksAI",
    greetingDesc: "Farklı konularda dilediğini sor — ödevler, kodlama, yaratıcı yazı yazma ve her türlü problem çözmede yardımcı olurum.",
    activeModelLabel: "Aktif Model",
    noCreditsText: "⚡ Krediniz kalmadı. Yarın otomatik olarak +100 kredi daha hesabınıza eklenecektir!",
    or: "veya",
    footerDisclaimer: "AleksAI tamamen ücretsizdir",
    activeTheme: "Görünüm:",
    activeSize: "Görünüm Modu:",
    activeLang: "Dil:",
    searchBtn: "Sor",
    selectPreferModel: "Sohbet için tercih ettiğiniz modeli seçin:",
    automaticSize: "Otomatik (Duyarlı)",
    mobileModel: "iPhone (Mobil)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Geniş Ekran)",
    german: "Almanca",
    english: "İngilizce",
    spanish: "İspanyolca",
    french: "Fransızca",
    italian: "İtalyanca",
    turkish: "Türkçe",
    serbian: "Sırpça",
    russian: "Rusça",
    portuguese: "Portekizce"
  },
  sr: {
    welcome: "Dobrodošli u AleksAI. Intelegence",
    subtitle: "Vaš pametni, besplatni AI saputnik",
    homeTitle: "AI razgovori redefinisani.",
    homeSubtitle: "Postavljajte neograničena pitanja. Dobijte visoko precizne odgovore. Uživajte u besplatnom pristupu premium modelima.",
    placeholderHome: "Pitajte besplatno ... promenjeno u vaš omiljeni model.",
    placeholderChat: "Pitajte AleksAI...",
    suggestedQuanten: "⚛️ Kvantna fizika",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Saveti za san",
    suggestedScharze: "🌌 Crne rupe",
    advantages: "Prednosti",
    whyUs: "Zašto AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 kredita dnevno",
    benefitsCreditsDesc: "Dobijajte automatski 100 besplatnih energetskih kredita svakog dana. 1 kredit predstavlja jednu AI interakciju.",
    benefitsModelsTitle: "5 integrisanih AI modela",
    benefitsModelsDesc: "Prebacujte se u bilo kom trenutku između AleksAI Max, Pro, neo, Ultra i buissnis.",
    benefitsAccountTitle: "Siguran korisnički nalog",
    benefitsAccountDesc: "Registrujte se bezbedno sa korisničkim imenom. Vaša istorija se čuva privatno na vašem uređaju.",
    benefitsFreeTitle: "100% Besplatno",
    benefitsFreeDesc: "Nema pretplata niti unosa kartica. Platforma je i ostaće potpuno besplatna za sve korisnike.",
    login: "Prijavi se",
    register: "Registruj se",
    guestLogin: "Prijavi se kao gost",
    guestBadge: "👤 Prijavi se kao Gost i nastavi",
    logout: "Odjavi se",
    newChat: "Novi razgovor",
    noChats: "Nema sačuvanih razgovora.",
    credits: "Energetski krediti",
    creditsRefilled: "🎁 Vaših dnevnih +100 gratis kredita je dopunjeno!",
    settings: "Podešavanja",
    settingsTitle: "Podešavanja za AleksAI. Intelegence",
    settingsModel: "Izaberite model",
    settingsTheme: "Izgled",
    settingsSize: "Veličina ekrana / Prikaz",
    settingsLanguage: "Promenite jezik",
    close: "Zatvori",
    username: "Korisničko ime",
    password: "Lozinka",
    profile: "Profil",
    chat: "Ćaskanje",
    greeting: "Zdravo! Ja sam AleksAI",
    greetingDesc: "Postavi mi pitanje — pomažem oko domaćih zadataka, programiranja, pisanja tekstova, kreativnog sadržaja i još mnogo toga.",
    activeModelLabel: "Aktivni model",
    noCreditsText: "⚡ Nemate više kredita. Vaš nalog će automatski dobiti još +100 kredita sutra!",
    or: "ili",
    footerDisclaimer: "AleksAI je potpuno besplatan",
    activeTheme: "Izgled:",
    activeSize: "Režim prikaza:",
    activeLang: "Jezik:",
    searchBtn: "Pitaj",
    selectPreferModel: "Izaberite željeni model za razgovor:",
    automaticSize: "Automatski (Prilagodljivo)",
    mobileModel: "iPhone (Mobilni)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Široki ekran)",
    german: "Nemački",
    english: "Engleski",
    spanish: "Španski",
    french: "Francuski",
    italian: "Italijanski",
    turkish: "Turski",
    serbian: "Srpski",
    russian: "Ruski",
    portuguese: "Portugalski"
  },
  ru: {
    welcome: "Добро пожаловать в AleksAI. Intelegence",
    subtitle: "Ваш умный, бесплатный ИИ-помощник",
    homeTitle: "Общение с ИИ на новом уровне.",
    homeSubtitle: "Задавайте любые вопросы. Получайте точные ответы. Бесплатный доступ к премиум-моделям.",
    placeholderHome: "Задать вопрос бесплатно ... переключено на любимую модель.",
    placeholderChat: "Спросите AleksAI...",
    suggestedQuanten: "⚛️ Квантовая физика",
    suggestedPython: "🐍 Python Фибоначчи",
    suggestedSchlaf: "💤 Советы для сна",
    suggestedScharze: "🌌 Черные дыры",
    advantages: "Преимущества",
    whyUs: "Почему AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 кредитов ежедневно",
    benefitsCreditsDesc: "Каждый день автоматически получайте 100 бесплатных кредитов энергии. 1 кредит равен 1 запросу.",
    benefitsModelsTitle: "5 встроенных ИИ-моделей",
    benefitsModelsDesc: "Переключайтесь в любое время между AleksAI Max, Pro, neo, Ultra и buissnis.",
    benefitsAccountTitle: "Безопасный профиль",
    benefitsAccountDesc: "Зарегистрируйтесь под своим именем. История чатов конфиденциально хранится только на вашем устройстве.",
    benefitsFreeTitle: "100% бесплатно",
    benefitsFreeDesc: "Никаких подписок или оплаты картой. Платформа всегда была и останется бесплатной для всех.",
    login: "Войти",
    register: "Регистрация",
    guestLogin: "Войти как гость",
    guestBadge: "👤 Войти как Гость и продолжить",
    logout: "Выйти",
    newChat: "Новый чат",
    noChats: "История чатов пуста.",
    credits: "Кредиты энергии",
    creditsRefilled: "🎁 Ваши ежедневные +100 бесплатных кредитов обновлены!",
    settings: "Настройки",
    settingsTitle: "Настройки AleksAI. Intelegence",
    settingsModel: "Выбрать модель",
    settingsTheme: "Внешний вид",
    settingsSize: "Размер экрана / Режим",
    settingsLanguage: "Сменить язык",
    close: "Закрыть",
    username: "Имя пользователя",
    password: "Пароль",
    profile: "Профиль",
    chat: "Чат",
    greeting: "Привет! Я AleksAI",
    greetingDesc: "Задайте мне любой вопрос — я помогу с уроками, кодом, текстом, креативным контентом и многим другим.",
    activeModelLabel: "Активная модель",
    noCreditsText: "⚡ Нет кредитов. Завтра вы автоматически получите новые +100 кредитов!",
    or: "или",
    footerDisclaimer: "AleksAI абсолютно бесплаten",
    activeTheme: "Тема:",
    activeSize: "Режим экрана:",
    activeLang: "Язык:",
    searchBtn: "Спросить",
    selectPreferModel: "Выберите модель для общения:",
    automaticSize: "Автоматически (Адаптивный)",
    mobileModel: "iPhone (Мобильный)",
    tabletModel: "iPad (Планшет)",
    desktopModel: "PC (Широкий экран)",
    german: "Немецкий",
    english: "Английский",
    spanish: "Испанский",
    french: "Французский",
    italian: "Итальянский",
    turkish: "Турецкий",
    serbian: "Сербский",
    russian: "Русский",
    portuguese: "Португальский"
  },
  pt: {
    welcome: "Bem-vindo ao AleksAI. Intelegence",
    subtitle: "Seu companheiro inteligente e gratuito de IA",
    homeTitle: "Conversas com IA Redefinidas.",
    homeSubtitle: "Faça perguntas ilimitadas. Obtenha respostas de alta precisão. Desfrute de acesso gratuito a modelos de ponta.",
    placeholderHome: "Pergunte de graça ... alternado para o seu modelo favorito.",
    placeholderChat: "Pergunte ao AleksAI...",
    suggestedQuanten: "⚛️ Física quântica",
    suggestedPython: "🐍 Python Fibonacci",
    suggestedSchlaf: "💤 Dicas de sono",
    suggestedScharze: "🌌 Buracos Negros",
    advantages: "Vantagens",
    whyUs: "Por que AleksAI. Intelegence?",
    benefitsCreditsTitle: "+100 créditos diários",
    benefitsCreditsDesc: "Ganhe automaticamente 100 créditos de energia gratuitos todos os dias. 1 crédito equivale a 1 consulta.",
    benefitsModelsTitle: "5 modelos de IA integrados",
    benefitsModelsDesc: "Alterne a qualquer momento entre AleksAI Max, Pro, neo, Ultra e buissnis.",
    benefitsAccountTitle: "Conta de usuário segura",
    benefitsAccountDesc: "Cadastre-se com segurança. Seu histórico é guardado de forma privada no seu dispositivo.",
    benefitsFreeTitle: "100% Gratuito",
    benefitsFreeDesc: "Sem assinaturas ou cartões de crédito. A plataforma é e continuará totalmente grátis para todos.",
    login: "Entrar",
    register: "Cadastrar-se",
    guestLogin: "Entrar como convidado",
    guestBadge: "👤 Entrar como Convidado e continuar",
    logout: "Sair",
    newChat: "Nova conversa",
    noChats: "Nenhum histórico disponível.",
    credits: "Créditos de energia",
    creditsRefilled: "🎁 Seus +100 créditos gratuitos diários foram recarregados!",
    settings: "Configurações",
    settingsTitle: "Configurações do AleksAI. Intelegence",
    settingsModel: "Selecionar modelo",
    settingsTheme: "Tema",
    settingsSize: "Tamanho de tela / Modo",
    settingsLanguage: "Mudar idioma",
    close: "Fechar",
    username: "Nome de usuário",
    password: "Senha",
    profile: "Perfil",
    chat: "Chat",
    greeting: "Olá! Eu sou o AleksAI",
    greetingDesc: "Faça-me uma pergunta — te ajudo com lição de casa, código, textos bonitos, criação de conteúdo e muito mais.",
    activeModelLabel: "Modelo ativo",
    noCreditsText: "⚡ Sem créditos restantes. Você receberá +100 créditos automaticamente amanhã!",
    or: "ou",
    footerDisclaimer: "AleksAI é totalmente gratuito",
    activeTheme: "Visual:",
    activeSize: "Modo de exibição:",
    activeLang: "Idioma:",
    searchBtn: "Perguntar",
    selectPreferModel: "Selecione seu modelo preferido para conversar:",
    automaticSize: "Automático (Responsivo)",
    mobileModel: "iPhone (Telemóvel)",
    tabletModel: "iPad (Tablet)",
    desktopModel: "PC (Widescreen)",
    german: "Alemão",
    english: "Inglês",
    spanish: "Espanhol",
    french: "Francês",
    italian: "Italiano",
    turkish: "Turco",
    serbian: "Sérvio",
    russian: "Russo",
    portuguese: "Português"
  }
};
